[package]
name = "sandvox"
description = "The 3D voxel falling-sand game"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]

[dependencies]
glium = "*"
cgmath = "0.16.1"
clamp = "0.1.0"
image = "0.20.1"
nd_iter = "0.0.4"
rand = "0.6.4"
rand_xorshift = "0.1.1"
